# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  clean:
    cmds:
      - find . -type d -name __pycache__ -exec rm -r {} +
    silent: true

  run:orders:
    cmds:
      - cd orders && poetry run uvicorn app:app --reload
    silent: true

  run:swagger-editor:
    cmds:
      - docker run -p 80:8080 -v $(pwd):/tmp -e SWAGGER_FILE=/tmp/oas.yaml swaggerapi/swagger-editor
    silent: true

  run:prism:
    cmds:
      - docker run --init --rm -v $(pwd):/tmp -p 4010:4010 stoplight/prism:4 mock -h 0.0.0.0 "/tmp/oas.yaml"
    silent: true

  run:kitchen:
    cmds:
      - cd kitchen && poetry run flask run --reload
